name: C Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GCC
      run: sudo apt-get install build-essential

    - name: Compile the project
      run: make all

    - name: Run the binary
      run: ./all.out
